# Generated by Django 4.1.7 on 2023-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chat_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(max_length=300),
        ),
    ]
